### ISSUE TITLE
Arguments of `GraphCallback` in wrong order?

### ISSUE THREAD

**Issue by ckristo** [rdf-ext-archive/rdf-ext-spec#6]
Hi,

I noticed that the arguments of `GraphCallback` as described in the spec do not match the implementation. The implementation follows the node call convention `function(err, graph)` whereas the spec defines it as `function(graph, err)`.

I'd suggest do change that in the spec to follow the node calling convention.

BR, Chris

**Comment by ckristo** [comment]
Noticed that other callbacks are also defined with `err` as their second argument (e.g. `DataCallback`); maybe change them as well?

**Comment by bergos** [comment]
Sorry, the HTML file is outdated. The [API.md](https://github.com/rdf-ext/rdf-ext-spec/blob/gh-pages/API.md) file contains a up-to-date API description. I will remove the HTML to avoid confusions in the future.
