### ISSUE TITLE
Arguments of `Store.match` in wrong order?

### ISSUE THREAD

**Issue by ckristo** [rdf-ext-archive/rdf-ext-spec#7]
Hi,

I noticed that the order of arguments of `Store.match` as defined by the specification differs from rdf-ext's implementation:

`Store.match(any? iri, any? subject, any? predicate, any? object, GraphCallback callback, optional unsigned long limit)`

whereas the implementation uses:

`AbstractStore.prototype.match = function (subject, predicate, object, iri, callback, limit)`

Best regards, Chris

**Comment by bergos** [comment]
Sorry, the HTML file is outdated. The [API.md](https://github.com/rdf-ext/rdf-ext-spec/blob/gh-pages/API.md) file contains a up-to-date API description. I will remove the HTML to avoid confusions in the future.
